/** @type {import('tailwindcss').Config} */

// Helper: wrap CSS variable RGB channels for Tailwind's opacity interpolation
const c = (varName) => `rgb(var(${varName}) / <alpha-value>)`;

module.exports = {
  darkMode: ["selector", "[data-theme='dark']"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: c("--color-border"),
        input: c("--color-input"),
        ring: c("--color-ring"),
        background: c("--color-background"),
        foreground: c("--color-foreground"),
        card: {
          DEFAULT: c("--color-card"),
          foreground: c("--color-card-foreground"),
        },
        popover: {
          DEFAULT: c("--color-popover"),
          foreground: c("--color-popover-foreground"),
        },
        primary: {
          DEFAULT: c("--color-primary-500"),
          foreground: c("--color-primary-foreground"),
          50: c("--color-primary-50"),
          100: c("--color-primary-100"),
          200: c("--color-primary-200"),
          300: c("--color-primary-300"),
          400: c("--color-primary-400"),
          500: c("--color-primary-500"),
          600: c("--color-primary-600"),
          700: c("--color-primary-700"),
          800: c("--color-primary-800"),
          900: c("--color-primary-900"),
          950: c("--color-primary-950"),
        },
        secondary: {
          DEFAULT: c("--color-secondary-500"),
          foreground: c("--color-secondary-foreground"),
          50: c("--color-secondary-50"),
          100: c("--color-secondary-100"),
          200: c("--color-secondary-200"),
          300: c("--color-secondary-300"),
          400: c("--color-secondary-400"),
          500: c("--color-secondary-500"),
          600: c("--color-secondary-600"),
          700: c("--color-secondary-700"),
          800: c("--color-secondary-800"),
          900: c("--color-secondary-900"),
          950: c("--color-secondary-950"),
        },
        muted: {
          DEFAULT: c("--color-muted"),
          foreground: c("--color-muted-foreground"),
        },
        accent: {
          DEFAULT: c("--color-accent"),
          foreground: c("--color-accent-foreground"),
        },
        destructive: {
          DEFAULT: c("--color-destructive"),
          foreground: c("--color-destructive-foreground"),
        },
        success: {
          DEFAULT: c("--color-success-500"),
          50: c("--color-success-50"),
          100: c("--color-success-100"),
          200: c("--color-success-200"),
          300: c("--color-success-300"),
          400: c("--color-success-400"),
          500: c("--color-success-500"),
          600: c("--color-success-600"),
          700: c("--color-success-700"),
          800: c("--color-success-800"),
          900: c("--color-success-900"),
          950: c("--color-success-950"),
        },
        warning: {
          DEFAULT: c("--color-warning-500"),
          50: c("--color-warning-50"),
          100: c("--color-warning-100"),
          200: c("--color-warning-200"),
          300: c("--color-warning-300"),
          400: c("--color-warning-400"),
          500: c("--color-warning-500"),
          600: c("--color-warning-600"),
          700: c("--color-warning-700"),
          800: c("--color-warning-800"),
          900: c("--color-warning-900"),
          950: c("--color-warning-950"),
        },
        error: {
          DEFAULT: c("--color-error-500"),
          50: c("--color-error-50"),
          100: c("--color-error-100"),
          200: c("--color-error-200"),
          300: c("--color-error-300"),
          400: c("--color-error-400"),
          500: c("--color-error-500"),
          600: c("--color-error-600"),
          700: c("--color-error-700"),
          800: c("--color-error-800"),
          900: c("--color-error-900"),
          950: c("--color-error-950"),
        },
        info: {
          DEFAULT: c("--color-info-500"),
          50: c("--color-info-50"),
          100: c("--color-info-100"),
          200: c("--color-info-200"),
          300: c("--color-info-300"),
          400: c("--color-info-400"),
          500: c("--color-info-500"),
          600: c("--color-info-600"),
          700: c("--color-info-700"),
          800: c("--color-info-800"),
          900: c("--color-info-900"),
          950: c("--color-info-950"),
        },
      },
      borderRadius: {
        lg: "0.5rem",
        md: "0.375rem",
        sm: "0.25rem",
        xl: "0.75rem",
        "2xl": "1rem",
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'Cascadia Code', 'monospace'],
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
