import { Injectable, Logger } from '@nestjs/common';
import { AgentService } from '../agent.service';
import { PrReviewService } from '../../pr-review/pr-review.service';
import { GitHubService } from '../../ingest/github.service';
import { AgentType, AgentTrigger } from '../../entities/agent-run.entity';

@Injectable()
export class AgentPrService {
  private readonly logger = new Logger(AgentPrService.name);

  constructor(
    private readonly agentService: AgentService,
    private readonly prReviewService: PrReviewService,
    private readonly githubService: GitHubService,
  ) {}

  async runPrReview(
    repoId: string,
    repoFullName: string,
    prNumber: number,
    trigger: AgentTrigger,
  ): Promise<void> {
    let runId: string | undefined;

    try {
      // 1. Start Agent Run
      const run = await this.agentService.startRun(
        repoId,
        AgentType.PR_REVIEW,
        trigger,
        { prNumber, repo: repoFullName },
      );
      runId = run.id;

      this.logger.log(`Starting PR review agent run ${runId} for ${repoFullName}#${prNumber}`);

      // 2. Perform Review (using PrReviewService)
      const reviewResult = await this.prReviewService.reviewPullRequest(
        repoFullName,
        prNumber,
        { postComment: false, repoId },
      );

      // 3. Format Comment (Structured Review)
      const commentBody = this.formatReviewBody(reviewResult);

      // 4. Post Review
      const event =
        reviewResult.recommendation === 'approve'
          ? 'APPROVE'
          : reviewResult.recommendation === 'request_changes'
            ? 'REQUEST_CHANGES'
            : 'COMMENT';

      const { url } = await this.githubService.createPrReview(
        repoFullName,
        prNumber,
        commentBody,
        event,
        // Token is handled inside GitHubService via repo config
      );

      // 5. Complete Run
      const tokensUsed = reviewResult.tokensUsed ?? 0;
      if (reviewResult.prReviewId) {
        await this.agentService.completeRun(runId, reviewResult.findings.length, tokensUsed, {
          prReviewId: reviewResult.prReviewId,
        });
      } else {
        await this.agentService.completeRun(runId, reviewResult.findings.length, tokensUsed);
      }

      this.logger.log(`Completed PR review agent run ${runId}: ${url}`);

    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.error(`PR review agent failed: ${msg}`);
      if (runId) {
        await this.agentService.failRun(runId, msg);
      }
      throw err; // Retry by Bull
    }
  }

  private formatReviewBody(review: any): string {
    const emoji = review.score >= 80 ? '✅' : review.score >= 60 ? '⚠️' : '❌';
    const recLabel: Record<string, string> = {
      approve: 'Approve',
      request_changes: 'Request Changes',
      comment: 'Comment',
    };

    let body = `## 🤖 CodeRover Agent Review\n\n`;
    body += `${emoji} **Score: ${review.score}/100** | **${recLabel[review.recommendation] ?? review.recommendation}**\n\n`;
    body += `### Summary\n${review.summary}\n\n`;

    if (review.findings && review.findings.length > 0) {
      body += `### Findings\n\n`;
      const grouped: Record<string, any[]> = {};
      for (const f of review.findings) {
        if (!grouped[f.severity]) grouped[f.severity] = [];
        grouped[f.severity].push(f);
      }

      const severities = ['critical', 'warning', 'suggestion', 'info'];
      const sevEmoji: Record<string, string> = {
        critical: '🔴',
        warning: '🟡',
        suggestion: '🔵',
        info: 'ℹ️',
      };

      for (const sev of severities) {
        if (grouped[sev]?.length) {
          body += `**${sevEmoji[sev] ?? ''} ${sev.toUpperCase()}**\n`;
          for (const f of grouped[sev]) {
             const loc = f.line ? `\`${f.file}:${f.line}\`` : `\`${f.file}\``;
             body += `- ${loc}: ${f.message} *(${f.category})*\n`;
          }
          body += '\n';
        }
      }
    } else {
        body += `### Findings\nNo issues found. ✨\n\n`;
    }

    body += `---\n*Generated by CodeRover Phase 8 Agent*`;
    return body;
  }
}
